### PR TITLE
Improve Cabal site styling and content organization.

### PR DESCRIPTION
**Pull request by m-renaud**
# Overview

Restyle and re-organize content on the Cabal website. This isn't meant to be a full rewrite, only an incremental improvement on what's there now.

## High Level Changes

- Make the site work well on mobile.
- Consistent styling/layout across pages.
- Organize content to focus on cabal-install and install/upgrade process.

## Viewing the Changes

Visit https://www.m-renaud.com/sites/haskell-org/cabal/

### CODE REVIEW

**Comment by phadej** [comment]
Let's either change the content, or change the styling. There is too much to much pieces in this bike shed.. to begin:
- I'm a bit tired of this violet color scheme. This colors and fonts are however different than used on hackage.haskell.org or www.haskell.org. I'd say, let's pick some other colors, or then copy the typography & basic color scheme from either one.
- If we gonna mention ghcup, than we need to explicitly mention hvr ppa, brew, chocolatey. Again, let's have the `cabal install cabal-install` and binary options as the first one. There is a reason: those are the only Cabal's release manager has an ultimate control over.
    - or better: let's not edit the content now at all. It's tempting, but we'll agree on one thing at the time much quicker. This PR is a single commit which does everything at once, IMO it's too "big" change to discuss.

Note: The Hackage style change was long and partly unproductive discussion, as both layout and color scheme were changed a lot at once.

**Comment by m-renaud** [comment]
> Let's either change the content, or change the styling

These two are somewhat intertwined, a lot of the HTML changes are reformatting or adding spans and classes to enable the restyle. If you take a look at the live changes it contains the same information in a more digestible presentation.

In terms of content I have changed, I've reordered some sections and added some more detail but haven't substantially edited the content.

Also, the current formatting of the HTML files is a mess and a lot of the diffs there are just formatting adding missing `<p>` or close tags, and to keep me sane when reading it. We could even do a PR just to reformat them so that the follow up changes look cleaner, but then there could be push back over "a format only change isn't valuable", so I'd argue to just do them together.

> If we gonna mention ghcup, than we need to explicitly mention hvr ppa, brew, chocolatey.

I can leave those changes to a follow up if you'd like.

> I'm a bit tired of this violet color scheme

That's fair, I just took colors from the haskell logo and used those. I'm open to suggestions, but against the current blue colours since the bright blue is reminiscent of links and doesn't fit with any of the other haskell sites. Shades of dark gray I'd be in favour of. I think the violet theme is better than the current one though.

> The Hackage style change was long and partly unproductive discussion

I don't want the same thing to happen here. The current layout and organization makes it hard to find what you're looking for. It would be unfortunate if a bikeshed on heading colours blocked the other improvements :)

Maybe it's just me but I feel like a clean edit history of an HTML or css file that can be tweaked in the future isn't as important as code.

Also, this chance is significantly smaller in scope than the hackage redesign. Are there any hard blockers about this change or just small commit organization and style nits?

Edit: typos because phone

**Comment by 23Skidoo** [comment]
The [download page](https://www.m-renaud.com/sites/haskell-org/cabal/download.html) looks kinda ugly, can we make everything left-aligned?

Otherwise, this is a good first step in improving the website, and I'd prefer to merge it as-is rather than waste time bikeshedding.

**Comment by 23Skidoo** [comment]
@m-renaud Note that there is also the `feature/next` branch, which is the most recent attempt at improving the website.

**Comment by m-renaud** [comment]
@23Skidoo 

> The download page looks kinda ugly, can we make everything left-aligned?

Oops, somehow ended up with a spurious table tag at the start of it.

> I'd prefer to merge it as-is rather than waste time bikeshedding.

+1, sgtm. There's definitely still more tweaks and improvements we can do, but lets leave them for follow-ups.

> Note that there is also the feature/next branch

I saw that and I like it :) I figured these changes will eventually be replaced by that but it wasn't clear how far off that will be since its a more ambitious redesign, I figured the changes here would be a decent stop gap in the meantime :)

**Comment by 23Skidoo** [comment]
> I figured the changes here would be a decent stop gap in the meantime :)

SGTM. Let's merge!

**Comment by 23Skidoo** [comment]
This is now up on http://haskell.org/cabal.

**Pull request merged**
