### PR TITLE
Get index.html in synch with cabal/README.md and update it a bit

### PR DESCRIPTION
**Pull request by Mikolaj**
I guess, ideally, we should somehow deduplicate the numerous cabal upgrading/installation advice snippets in various places. For now, I've got this one in sync and linked to the more up-to-date and more detailed (for source installs only) cabal/README.md.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Hi @emilypi and @simonmichael! Would you like to make a quick review of this commit before I merge or do you know of somebody who might be a good fit, e.g., somebody more of less formally maintaining the documentation or the webpage? I will be coordinating the cabal work, but right now I'm a newbie, so any hints and any help would be very welcome. :)

**Review by emilypi — APPROVED** [review]
Thanks @Mikolaj - this generally makes sense and thank you for the update!

> somebody who might be a good fit, e.g., somebody more of less formally maintaining the documentation or the webpage? I will be coordinating the cabal work, but right now I'm a newbie, so any hints and any help would be very welcome. :)

Technically that's me atm, though i'm keeping it on life support rather than maintaining

**Comment by Mikolaj** [comment]
Thank you @emilypi --- it looks pretty much alive. Let's keep it that way.

**Comment by Mikolaj** [comment]
@emilypi: I don't think the new version of the page is going to auto-deploy, because I can still see the old one at https://www.haskell.org/cabal/

Does it need any manual prodding?

**Comment by emilypi** [comment]
Yeah, it takes a manual deploy via sftp. I'll do it today , haven't had time.

**Comment by Mikolaj** [comment]
Oh, I didn't intend to badger you. :) Thanks.

**Comment by emilypi** [comment]
Bumping is a good way to keep things on my radar :)

**Pull request merged**
