### PR TITLE
Fix download link for linux

### PR DESCRIPTION
**Pull request by jneira**
* As reported in https://github.com/haskell/cabal/issues/7994 and https://github.com/haskell/cabal/issues/8001

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Thank you. Do you intend to upload this or should I?

**Comment by jneira** [comment]
Afaik i dont have perms to upload, which tbh is the hard work here :slightly_smiling_face:

**Comment by Mikolaj** [comment]
Done. The real hard work comes now, which is waiting dozens of hours until CDN kicks in and syncs their cache of the webpage. :)

**Comment by Mikolaj** [comment]
And, strangely, this time it happened instantaneously.

**Pull request merged**
