### PR TITLE
3.12 page

### PR DESCRIPTION
**Pull request by ffaf1**
Minor updated to the download page for 3.12.

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]

**Comment by ulysses4ever** [comment]
Thanks Francesco! 

TWIMC: we'll need to deploy after the merge

**Comment by ulysses4ever** [comment]
@Mikolaj could you deploy?

**Comment by Mikolaj** [comment]
Will do!

**Comment by Mikolaj** [comment]
Done. This is indeed easy, just as in https://github.com/haskell/cabal/wiki/Making-a-release#c6-publishing-everything-else, and I do have the required permissions.

**Comment by ulysses4ever** [comment]
It's still one extra step that requires a person with permissions, so we can't employ volunteers like for most other steps. I think we should consider improving the workflow so that every commit on the master branch gets deployed automatically. There are several ways to skin this cat. I'd be interested to talk about it on a cabal meeting....

**Comment by ulysses4ever** [comment]
But thank you!

**Pull request merged**
